### ISSUE TITLE
Source list

### ISSUE THREAD

**Issue by bjswift** [khufkens/pi-camera-response-curves#1]
Hi! Thanks, this is great! :)  Could you please provide the community with the data you used to generate these, and the method? Links to and/or copies of the plot images you used (I think that's what you meant that you did) and even just a "I multiplied these curves together" if that's what happened. Cheers!

**Comment by khufkens** [comment]
I put the original post, [mentioning the IMX specs](https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=145815&start=50#p962746) on the raspberry pi forum, on my webpage. 

Data was digitized using this [online plot digitizer](http://arohatgi.info/WebPlotDigitizer/), cleaned up for digitization mismatches and interpolated using smoothing spline.

The same workflow was used for both sensors.

**Comment by bjswift** [comment]
Ah, thanks. I just finally saw the same exact shapes in that plot. I thought that perhaps you'd generated it from separate plots of the unfiltered pixel spectral QE and color transmission curves.

**Comment by khufkens** [comment]
This is all based upon spec sheets, not physical measurements. The NIR is sadly missing (as these are de-facto VIS sensors).

**Comment by bjswift** [comment]
Yes, that is what I was interested in as well :) for some planning purposes. At least a good guess (probably to 5%) can be made from published sensitivity functions of other similar Sony products.

**Comment by khufkens** [comment]
Please do share your findings, especially the NIR is of interest to me for vegetation index applications.

I haven't had time to invest in determining the NIR part myself.

**Comment by bjswift** [comment]
Also, I don't believe the y-axes in your plots should be QE, but rather "relative response", since QE is never going to be that high.

I put together a little something which gave me good guidelines to let me literally sketch out what the RGB response curves probably look like out in the near-IR. This is based on what I've seen that CMOS detector responses and RGB filter responses have very similar bumps and wiggles in the response function across a broad range of products.

![sonyimx219withnirestimate_v_similarcmos](https://cloud.githubusercontent.com/assets/13608172/16017143/6ae28b7e-3153-11e6-9c37-689416000b5a.png)

Take it with a heaping tablespoon of salt, as it's intended to only be schematic, but useful in that we can have some kind of reasonable numerical estimates to use where it's reasonable. If you like, I can issue a pull request with my subdirectory that includes all my code, generated data, and notes.

**Comment by khufkens** [comment]
The values for the OV sensor peak at ~56% (of the current range) if I'm not mistaken, haven't looked up the value for the IMX sensor. The values are scaled 0 - 100 and need a multiplier to get back to the true QE, indeed. I mention this on my personal webpage only, not the github page. For bandpass filter applications QE doesn't matter too much, only the relative response.

And yes, those extrapolations would be very useful.

**Comment by bjswift** [comment]
Thanks for adding me. This is actually the first time I've contributed to an outside source, so I probably shouldn't have merged it without having you review it first. Sorry about that.

**Comment by khufkens** [comment]
I can revert it, I'll clean it up a bit.

**Comment by bjswift** [comment]
I fixed it already
